#correndo janelas 
#!/bin/bash
#PBS -l select=1:ncpus=16
#PBS -l walltime=5000:00:00
#PBS -N loStruct
#PBS -j oe
#PBS -m ae
#PBS -M gthomesilva@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH
export XDG_CACHE_HOME=/nas4/gthomesilva/:$XDG_CACHE_HOME

source activate lostruct
#keeping chr only
#grep \#\#contig SNP-only_filtered_ind_removed.recode.vcf | grep chr | perl -p -w -e 's/##contig=<ID=//g ; s/,length=/ 0 /g; s/>//g' > chromossomes.txt
#vcftools --vcf SNP-only_filtered_ind_removed.recode.vcf --bed chromossomes.txt --recode --out SNP_chr_only.vcf

#Converting vcf to bcf
#bcftools convert -O b SNP_chr_only.vcf.recode.vcf > data/SNP_chr_only.bcf
#bcftools index data/SNP_chr_only.bcf

module load R-3.4.1

Rscript run_lostruct.R -i data/ -I PP-sample_info.tsv -t SNP -s 1000 -M 0.5 -o results