#!/bin/bash
#PBS -l select=2:ncpus=64:mem=32gb
#PBS -l walltime=5000:00:00
#PBS -N BWA_alignment
#PBS -j oe
#PBS -m ae
#PBS -M gthomesilva@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH
#cd /home/gthomesilva/nas4

#Arguments:
##ref=reference/pseudochromosomesSHORT.fasta

date
time

module load bwa-0.7.15
module load fastqc-0.11.5
module load R-3.4.1
module load parallel-20171122
#source activate stampy

#ls raw_data/*.gz | perl -p -w -e 's/raw_data\///g;s/_R.*//g' | uniq > 1_samples_names.txt

###Create a samples_name file listing all the samples. Create a folder called clean to store trimmomatic outputs
cat 1_samples_names.txt | sed '/TP/d' | parallel -j 20 java -jar /home/gthomesilva/nas4/programs/Trimmomatic-0.36/trimmomatic-0.36.jar PE raw_data/FINAL_SEQ/tissue/raw_data/{}_R1.fastq.gz raw_data/FINAL_SEQ/tissue/raw_data/{}_R2.fastq.gz raw_data/FINAL_SEQ/tissue/clean/{}_R1_paired.fq.gz raw_data/FINAL_SEQ/tissue/clean/{}_R1_unpaired.fq.gz raw_data/FINAL_SEQ/tissue/clean/{}_R2_paired.fq.gz raw_data/FINAL_SEQ/tissue/clean/{}_R2_unpaired.fq.gz ILLUMINACLIP:/home/gthomesilva/nas4/programs/Trimmomatic-0.36/adapters/TruSeq3-PE-2.fa:2:30:10:8:true


