#!/bin/bash
#PBS -l select=1:ncpus=1
#PBS -l walltime=5000:00:00
#PBS -N GATK_SNP_select_variants
#PBS -j oe
#PBS -m ae
#PBS -M gthomesilvaa@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## vcf
vcf=phleg/vcf_files/allsamples.hardfiltered_best-pratice.recal.vcf
echo "#######################"
echo $vcf
echo "#######################"

echo
echo
echo Selecting Variants
echo
echo

vcftools \
--vcf $vcf \
--remove-indels \
--remove-filtered-all \
--max-missing 0.5 \
--min-alleles 2 \
--max-alleles 2 \
--mac 1 \
--minDP 4 \
--maxDP 40 \
--minGQ 20 \
--recode \
--out phleg/vcf_files/SNP-only_filtered
