#!/bin/bash
#PBS -l select=1:ncpus=24:mem=96G
#PBS -l walltime=5000:00:00
#PBS -N GATK_SNP_GVCF
#PBS -j oe
#PBS -m ae
#PBS -M gthomesilva@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH
module load parallel-20171122
#Arguments:
## ref=reference sequence

ref=reference/rhegma_ragout_complete.fasta

#you might have to adjust this line considering your individuals' names
vari=$(ls phleg/vcf_files/*.vcf | perl -p -w -e 's/phleg/--variant phleg/g; s/\n/ /g')
echo
echo
echo Combine GVCFs
echo
echo
mkdir phleg_tmp/

time java -Djava.io.tmpdir=phleg_tmp/ -jar programs/GenomeAnalysisTK-3.8-1-0-gf15c1c3ef/GenomeAnalysisTK.jar \
-T GenotypeGVCFs \
-R $ref \
$vari \
--heterozygosity 0.05 \
-o phleg/vcf_files/allsamples.raw.vcf

rm -r phleg_tmp/