sim.msABC.sumstat_new2 <- function (model, nsim.blocks, path = getwd(), use.alpha = F, 
          mu.rates = NULL, append.sims = F, block.size = 100, msABC.call = "/home/gthom/R/x86_64-pc-linux-gnu-library/3.6/PipeMaster/msABClinux", 
          output.name, ncores) 
{
  WD <- getwd()
  if (class(model) != "Model") {
    stop("First arguments should be an object of class Model generated by the main.menu() function.")
  }
  if (model$I[1, 1] == "genomic") {
    stop("You need to get the data structure first. See function get.data.structure")
  }
  setwd(path)
  locfile <- PipeMaster:::get.locfile(model)
  msABC.path <- find.package("PipeMaster")
  if (append.sims == F) {
    com <- PipeMaster:::msABC.commander(model, use.alpha = use.alpha, 
                                        arg = 1)
    write.table(locfile, paste(".", 1, "locfile.txt", sep = ""), 
                row.names = F, col.names = T, quote = F, sep = " ")
    options(warn = -1)
    x <- strsplit(system2(msABC.call, args = com[[1]], stdout = T, 
                          stderr = T, wait = T), "\t")
    options(warn = 0)
    nam <- x[1][[1]]
    cols <- grep("fwh", nam)
    cols <- c(cols, grep("thomson", nam))
    #cols <- c(cols, grep("ZnS", nam))
    cols <- c(cols, grep("_FayWuH", nam))
    if (length(cols) != 0) 
      nam <- nam[-cols]
    nam <- c(com[[2]][1, ], "mean.rate", "sd.rate","recomb", nam)
    write.table(t(nam), file = paste("SIMS_", output.name, 
                                     ".txt", sep = ""), quote = F, row.names = F, col.names = F, 
                append = F, sep = "\t")
  }
  write(paste("arg <- commandArgs(TRUE)", "cat(paste(\"Core\",arg),sep=\"\\n\")", 
              "suppressMessages(library(PipeMaster))", "load(file=\".PM_objects.RData\")", 
              "res<-sim.func(arg)", "save(res,file=paste(\".\",arg,\"_SIMS.rda\",sep=\"\"))", 
              "write(1,\".log\",append=T,sep=\"\\n\")", "invisible(file.remove(paste(\".\",arg,\"locfile.txt\",sep=\"\")))", 
              "quit(save='no')", sep = "\n"), ".script_parallel.R")
  sim.func <- function(arg) {
    simulations <- NULL
    
    #begin code again
        for (i in 1:block.size) {
      if (!(is.null(mu.rates))) {
        rates <- do.call(mu.rates[[1]], args = mu.rates[2:length(mu.rates)])
        rates <- rep(rates, each = as.numeric(model$I[1, 
                                                      3]))
        rates <- list(rates, c(0, 0))
      } else {
        rates <- PipeMaster:::sample.mu.rates(model)
      }
      #here i changed this argument to include a single value for the mutation rate
      #locfile[, 5] <- rates[[1]]
      locfile[, 5] <- rates[[2]][1]
      #Here I'll add a value for recombination rate on the locfile
      reco.pars <- t(as.matrix(c("recomb", "rec", "1", "0.0", "0.000000003021924", "runif")))
      #reco.pars <- t(as.matrix(c("recomb", "rec", "1", "0", "0", "runif")))
      reco.rate <- PipeMaster:::sample.pars(reco.pars)
      locfile[, 6] <- reco.rate[4]
      
      
      write.table(locfile, paste(".", arg, "locfile.txt", 
                                 sep = ""), row.names = F, col.names = T, quote = F, 
                  sep = " ")
      com <- PipeMaster:::msABC.commander(model, use.alpha = use.alpha, 
                             arg = arg)
      options(warn = -1)
      sumstat <- read.table(text = system2(msABC.call, 
                                           args = com[[1]], stdout = T, stderr = T, wait = T), 
                            header = T, sep = "\t")
      #system(paste(msABC.call, " ", com[[1]], sep = ""))
      
      options(warn = 0)
      sumstat <- subset(sumstat, select = -c(X))
      cols <- grep("fwh", colnames(sumstat))
      cols <- c(cols, grep("thomson", colnames(sumstat)))
      #cols <- c(cols, grep("ZnS", colnames(sumstat)))
      cols <- c(cols, grep("_FayWuH", colnames(sumstat)))
      if (length(cols) != 0) 
        sumstat <- sumstat[, -cols]
      param <- c(com[[2]][2, ], rates[[2]], reco.rate[4] )
      names(param) <- c(com[[2]][1, ], "mean.rate", "sd.rate", "recomb")
      simulations <- rbind(simulations, c(param, sumstat))
    }
    return(simulations)
  }
  parentls <- function() ls(envir = parent.frame())
  save(list = parentls(), file = ".PM_objects.RData")
  total.sims <- 0
  for (j in 1:nsim.blocks) {
    start.time <- Sys.time()
    write(0, ".log")
    for (c in 1:ncores) {
      system(paste("Rscript .script_parallel.R", c), wait = F)
    }
    l <- "0"
    while (sum(as.numeric(unlist(strsplit(l, "")))) < ncores) {
      Sys.sleep(5)
      l <- readLines(".log")
    }
    file.remove(".log")
    simulations <- NULL
    cat("Reading simulations from worker nodes", sep = "\n")
    for (c in 1:ncores) {
      load(file = paste(".", c, "_SIMS.rda", sep = ""))
      simulations <- rbind(simulations, res)
    }
    cat("Writing simulations to file", sep = "\n")
    write.table(simulations, file = paste("SIMS_", output.name, 
                                          ".txt", sep = ""), quote = F, row.names = F, col.names = F, 
                append = T, sep = "\t")
    cat("Removing old simulations", sep = "\n")
    for (t in 1:ncores) {
      file.remove(paste(".", t, "_SIMS.rda", sep = ""))
    }
    end.time <- Sys.time()
    total.sims <- total.sims + (block.size * ncores)
    cycle.time <- (as.numeric(end.time) - as.numeric(start.time))/60/60
    total.time <- cycle.time * nsim.blocks
    passed.time <- cycle.time * j
    remaining.time <- round(total.time - passed.time, 3)
    cat(paste("PipeMaster:: ", total.sims, " (~", round((block.size * 
                                                           ncores)/cycle.time), " sims/h) | ~", remaining.time, 
              " hours remaining", sep = ""), "\n")
  }
  setwd(WD)
}
